version: "3.3"

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./prisma/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    container_name: app
    build: 
      context: .
      dockerfile: app.prod.dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 5555:5555
      - 5173:5173
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
      - ORIGIN=https://cardboard.ink
      - ADDRESS_HEADER=True-Client-IP
      - PROTOCOL_HEADER=x-forwarded-proto # remove this if you're not using a reverse proxy (nginx, cloudflare etc.)
      - HOST_HEADER=x-forwarded-host # remove this if you're not using a reverse proxy (nginx, cloudflare etc.)